### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by HTU-cjd** [easechen/htu_health_check_in#13]
在腾讯云部署后，只显示成功登陆移动学工，但并未打卡，也未发送邮件
![Uploading 屏幕截图.jpg…]()

**Comment by easechen** [comment]
https://github.com/easechen/htu_health_check_in/commit/e819b5492c9c795a8aa538d1e20e69e5a91567e5
我已经注意到这个问题，请这样尝试修改`sign.py`试试。

**Comment by HTU-cjd** [comment]
第八行报错了：Unable to import 'Login' pylint(import-error)[8,1]

**Comment by easechen** [comment]
我这里导入包并没有什么问题，你可在自己的电脑上测试无误后再上传云函数中。
