### ISSUE TITLE
关于表单中form_id的重复性

### ISSUE THREAD

**Issue by zhu-jiyuan** [easechen/htu_health_check_in#3]
在签到提交的数据中，form_id每个人是不能重复的，重复会导致打卡信息同步会最后一个人的。

貌似，后端会分发一个form_id，以便于储存每个人的数据，前端的数据指向form_id的数据。

**Comment by easechen** [comment]
据我观察`form_id`每次提交的值都不一样，并随着提交次数的增加逐渐增加。它用可能用来标识一个提交记录，据我了解并不影响每个人的打卡记录。
但是为了更加具有通用性，我已进行了修复。

**Comment by zhu-jiyuan** [comment]
应该是固定的，刚查了一下15天前的抓包请求，每个人的form_id是固定不变的。

今天早上撞开了辅导员的后台账号，发现相同formID，公用一个ID数据同步。😰😰😰

获取上次打卡数据时，有时会遇到打卡数据错乱，比如温度栏是大沙漠🏜️

**Comment by easechen** [comment]
该问题已在[本次提交](https://github.com/easechen/htu_health_check_in/commit/09e72a2c0b2932242d7060141d1498ce2930d278)中进行了修复，感谢反馈。
欢迎提出issue和pr😀

**Comment by zhu-jiyuan** [comment]
我已经全部解决，并新增了教师登录和学生登录。打卡的位置信息自动选定上次的。
from_id是固定不变的，我使用了正则表达式，匹配出来了。
通过分析辅导员后台，数据同步可能是ip问题或者ua。
