### ISSUE TITLE
打卡问题

### ISSUE THREAD

**Issue by jackqwc** [easechen/htu_health_check_in#4]
邮件显示的是“打卡成功”，但是移动学工已填报记录里面没有，是我配置错了吗？

**Comment by easechen** [comment]
改问题已解决，请看[此处提交](https://github.com/easechen/htu_health_check_in/commit/d112724974b45b9204dbe369dc8d0ca9c5e9f0a3)。
由于html页面貌似更新了，导致获取不到正确的打卡链接，所以只需进行相应修改即可。

**Comment by jackqwc** [comment]
重新配置了一下，已经正常了，感谢！

**Comment by easechen** [comment]
不客气😀
