### ISSUE TITLE
打卡项目新增了两条

### ISSUE THREAD

**Issue by jackqwc** [easechen/htu_health_check_in#6]
![Screenshot_20210820_002243_com tencent mm](https://user-images.githubusercontent.com/66513765/130106023-7827795f-ba35-41fa-acc3-a0108f24b152.jpg)
自动打卡后发现新增了两条，希望作者更新下（这两条没填，自动打卡提交后不能修改了，这样的话会被学校检测到吗？）

**Comment by easechen** [comment]
今天晚些时候修复，所以今天需要手动修改一下。因为数据只能在当天修改，所以昨天的数据今天修改不了，你图上的已经过了12点。
会不会发现就不清楚了，自动打卡和普通的没什么区别~~，况且这打卡有点形式主义了，有记录就行了😮~~。

**Comment by jackqwc** [comment]
好的，谢谢😊

**Comment by easechen** [comment]
问题已经修复。本次更新增加了版本概念，在程序更新后，将会在打卡推送时的邮件中进行提醒。
