### ISSUE TITLE
又更新了

### ISSUE THREAD

**Issue by vegetablelong** [easechen/htu_health_check_in#7]
增加了一条学生身份
主要下面验证变了
该账号已绑定过微信，目前已无法再通过认证信息登录，您目前只能在之前绑定的微信号中直接登录。（稍后提供微信扫码登录以供电脑或其他设备使用。如果更换微信，请联系管理部门先解绑微信）

**Comment by easechen** [comment]
已看到，正在修复。

**Comment by vegetablelong** [comment]
> 已看到，正在修复。

看到修改了，很辛苦，休息一下，可以加上random GPS后面三位地址和触发之后随机sleep几分钟，因为有的个别LD闲得无聊专门找事儿，个别人已经被通知了（一会儿帮我删除掉这条，手动狗头）

**Comment by easechen** [comment]
会考虑你的建议，谢谢关心。等下就把这条删掉。🤫
