### ISSUE TITLE
统一认证网站的密码是多少啊

### ISSUE THREAD

**Issue by fgfxf** [easechen/htu_health_check_in#8]
我没有绑定手机和邮箱，目前是默认密码。但是试过了身份证后n位，后n位前n-1位等办法都不管用。

**Comment by fgfxf** [comment]
微信登录也不行

**Comment by easechen** [comment]
第一次登陆会提示修改密码，使用修改过的密码登陆。

**Comment by fgfxf** [comment]
> 第一次登陆会提示修改密码，使用修改过的密码登陆。

我登不进去，第一次密码是多少

**Comment by easechen** [comment]
我怎么会知道😓，我用的身份证后七位的前六位。

**Comment by jackqwc** [comment]
把你知道的密码都试试，或者点找回密码，或者让你辅导员给你重置密码
